networks:
  vulnet:
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  #starthere-demo:
  #   build:
  #     context: ./starthere
  #   ports:
  #     - "31337:31337"
  #   networks:
  #     - vulnet
  web01-demo:
    build:
      context: ./web01-demo
    networks:
      - vulnet
