networks:
    default:
      name: vulnet
      ipam:
        config:
          - subnet: 10.0.0.0/24

services:
  #attackbox:
  #  image: kalilinux/kali-rolling
  #  networks:
  #    - vulnet
  #starthere:
  #   build:
  #     context: ./starthere
  #   ports:
  #     - "31337:31337"
  #   networks:
  #     - vulnet
  web01:
    build:
      context: ./web01
    ports:
       - "80:80"
